### ISSUE TITLE
Error while running on Mac OS X Mavericks 

### ISSUE THREAD

**Issue by walidlaribi** [Alfanous-team/alfanous#338]
$ alfanous-console -h
Traceback (most recent call last):
  File "/usr/local/bin/alfanous-console", line 8, in <module>
    load_entry_point('alfanous==0.7.01', 'console_scripts', 'alfanous-console')()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 318, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2221, in load_entry_point
    return ep.load()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 1954, in load
    entry = **import**(self.module_name, globals(),globals(), ['**name**'])
  File "build/bdist.linux-i686/egg/alfanous/console.py", line 28, in <module>
  File "build/bdist.linux-i686/egg/alfanous/Outputs.py", line 30, in <module>
  File "build/bdist.linux-i686/egg/alfanous/main.py", line 23, in <module>
  File "build/bdist.linux-i686/egg/alfanous/Searching.py", line 24, in <module>
  File "build/bdist.linux-i686/egg/alfanous/QueryProcessing.py", line 78, in <module>
  File "build/bdist.linux-i686/egg/alfanous/Misc.py", line 18, in <module>
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 511, in getdefaultlocale
    return _parse_localename(localename)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 443, in _parse_localename
    raise ValueError, 'unknown locale: %s' % localename
ValueError: unknown locale: UTF-8

**Comment by sneetsher** [comment]
I couldn't reproduce this bug in in MacOS High Sierra 10.13 . 

```
$ env | grep LC_
LC_CTYPE=UTF-8
```
