### ISSUE TITLE
Could not run alfanous-desktop because of 'ImportError: cannot import name QtWebKit'

### ISSUE THREAD

**Issue by nrfaikar** [Alfanous-team/alfanous#478]
Traceback (most recent call last):
  File "/usr/bin/alfanous-desktop", line 11, in <module>
    load_entry_point('alfanousDesktop==0.7.23', 'gui_scripts', 'alfanous-desktop')()
$ alfanous-desktop  
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 570, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2751, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2405, in load
    return self.resolve()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2411, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/site-packages/alfanousDesktop/Gui.py", line 28, in <module>
    from PySide import  QtGui, QtCore, QtWebKit
ImportError: cannot import name QtWebKit

**Comment by sneetsher** [comment]
@nrfaikar , Could you please elaborate with more info about the environment? 
- What is operating system? and which release/version?
- How did you get alfanous & which instructions used for installation?

**Comment by nrfaikar** [comment]
OS: Linux 4.14.14
Distros: Solus
Installation: sudo pip install alfanousDesktop

**Comment by sneetsher** [comment]
I don't have experience `eopkg` package manager of Solus neither the system itself. 

The error seems due to missing dependency lib (Qt/PySide)  or not found by alfanous launcher.

Needed dependencies are list at bottom of this doc https://github.com/Alfanous-team/alfanous/blob/master/INSTALL.rst
